In [2]:
import pandas as pd
print(pd.__version__)
#Подключение библиотеки для работы с таблицами

2.3.3

In [ ]:
df= pd.read_csv(r'C:\Users\nikry\project-for-study\data\students.csv', delimiter = ',') 
#чтение csv файла и загрузка в пременную

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    str
 23  Sex                          186 non-null    str
 24  Problems in last semester    186 non-null    str
 25  Coin                         186 non-null    str
 26  Rock paper scissors          186 non-null    str
 27  Animal                       186 non-null    str
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    str
 30  Fastfood                     186 non-null    str
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    str
 35  Hostel                       186 non-null    str
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    str
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    str
 42  Your insitute                186 non-null    str
 43  Brother-sister               186 non-null    str
 44  Plane seat                   186 non-null    str
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), str(15)
memory usage: 69.9 KB

Математические методы pandas

In [6]:
df['Growth'].mean()
#метод вычисления среднего значения

np.float64(170.66129032258064)

In [7]:
df['Weight'].mean()
#метод вычисления среднего значения

np.float64(64.03184713375796)

In [8]:
df['Growth'].describe()
#проверка совпадения среднего значения

count    186.000000
mean     170.661290
std        9.055881
min      153.000000
25%      164.000000
50%      169.000000
75%      178.000000
max      197.000000
Name: Growth, dtype: float64

In [9]:
df['Growth'].median()
#вывод медианы (50%)

np.float64(169.0)

In [10]:
df['Weight'].median()
#вывод медианы (50%)

np.float64(60.0)

In [11]:
df['Growth'].min()
#вывод минимального значения

np.int64(153)

In [12]:
df['Weight'].min()
#вывод минимального значения

np.float64(3.0)

In [13]:
df['Weight'].max()
#вывод максимального значения

np.float64(120.0)

In [14]:
df['Rock paper scissors'].value_counts()

Rock paper scissors
Ножницы    88
Камень     60
Бумага     38
Name: count, dtype: int64

In [15]:
df['Growth'].min(), df['Growth'].max(), df['Growth'].std()

(np.int64(153), np.int64(197), np.float64(9.055880959226972))

Извлечение нужных столбцов из таблицы

In [16]:
df_cut = df[['Growth', 'Weight', 'Sex', 'Age']]
#оставляем только нужные столбцы

In [17]:
df_cut.info()

<class 'pandas.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Growth  186 non-null    int64
 1   Weight  157 non-null    float64
 2   Sex     186 non-null    str
 3   Age     186 non-null    int64
dtypes: float64(1), int64(2), str(1)
memory usage: 5.9 KB

In [18]:
df_cut.head()

   Growth  Weight      Sex  Age
0     170    64.0  женский   20
1     191    73.0  мужской   22
2     172    60.0  мужской   21
3     168    59.0  женский   19
4     159    57.0  женский   23

In [19]:
df_cut2 = df[['Weight', 'Sex']]

In [20]:
df_cut2.head(10)

   Weight      Sex
0    64.0  женский
1    73.0  мужской
2    60.0  мужской
3    59.0  женский
4    57.0  женский
5    50.0  мужской
6    55.0  мужской
7   120.0  мужской
8    69.0  мужской
9    58.0  женский

Селекция и фильтрация данных таблицы

In [21]:
female = df[df['Sex'] == 'женский']
#создали новую таблицу, в которой находятся только женщины

In [22]:
female.head()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0
9,22,168,38,6,2000,297,71,5,0,0,...,40,Милки Вей,860.0,Математический и ИТ,СоцГум,есть брат,У окна (пардон: у иллюминатора),15,10.0,40.0
10,20,158,35,4,2001,1000,85,72,0,0,...,600,КитКат,800000.0,Педагогический,Естественный (биология-химия-физика-технари),есть и брат и сестра,У прохода,10,9.0,15.0

In [23]:
male = df[df['Sex'] == 'мужской']
male.head()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
5,18,177,40,2,2003,100,70,68,0,75,...,250,Сникерс,1200000.0,СоцГум,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),12,7.0,30.0
6,18,180,42,0,2004,0,66,4,0,0,...,30,Сникерс,700000.0,Педагогический,Юридический,есть брат,У окна (пардон: у иллюминатора),5,30.0,35.0
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0

In [24]:
female['Growth'].mean(), male['Growth'].mean()
#Нашли среднее значение роста у мужчин и женщин

(np.float64(165.725), np.float64(179.63636363636363))

In [25]:
female['Age'].mean(), male['Age'].mean()

(np.float64(21.033333333333335), np.float64(20.060606060606062))

In [26]:
female['Age'].median(), male['Age'].median()

(np.float64(20.0), np.float64(20.0))

In [27]:
female['Coin'].value_counts(), male['Coin'].value_counts()

(Coin
 Орел     64
 Решка    56
 Name: count, dtype: int64,
 Coin
 Орел     54
 Решка    12
 Name: count, dtype: int64)

In [ ]:
df1 = df[df['Growth'] < 165]
df2 = df[(df['Growth'] >= 165) & (df['Growth'] <= 175)]
df3 = df[df['Growth'] > 175]
#разделили студентов по росту на 3 группы:
#1) студенты с ростом меньше 165
#2) студенты с ростом 165 и больше и студеннты с ростом 175 и меньше
#3) студенты с ростом больше 175

In [29]:
df1['Growth'].mean(), df2['Growth'].mean(), df3['Growth'].mean()

(np.float64(160.66666666666666),
 np.float64(169.16),
 np.float64(182.10526315789474))

In [30]:
df[df['Age'] + df['Year of birth'] == 2022].shape
#посчитали количество студентов, у которых уже прошло ДР

(102, 48)

In [31]:
df[df['Growth'] < df['Growth'].mean()].shape
#нашли людей с ростом, который меньше среднего значения роста

(110, 48)

In [32]:
df[df['Age'] == df['Age'].min()]
#нашли людей с наименьшим возрастом

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
115,17,175,41,0,2004,152,96,80,0,83,...,1000,КитКат,1.0,СоцГум,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),3,2.0,5.0
126,17,168,39,0,2004,110,91,72,0,83,...,1000,Марс,800000.0,Экономический,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),5,7.0,15.0

In [33]:
df[df['Age'] == df['Age'].max()]
#нашли человека с наибольшем возрастом

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
81,55,160,37,7,1960,2000,0,0,0,0,...,300,Милки Вей,800000.0,СоцГум,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),10,10.0,10.0

In [34]:
df[df['Weight'] == df['Weight'].max()]

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0

Решение практических задач по второму уроку

In [35]:
pd.set_option('display.max_rows', 1000)

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    str
 23  Sex                          186 non-null    str
 24  Problems in last semester    186 non-null    str
 25  Coin                         186 non-null    str
 26  Rock paper scissors          186 non-null    str
 27  Animal                       186 non-null    str
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    str
 30  Fastfood                     186 non-null    str
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    str
 35  Hostel                       186 non-null    str
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    str
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    str
 42  Your insitute                186 non-null    str
 43  Brother-sister               186 non-null    str
 44  Plane seat                   186 non-null    str
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), str(15)
memory usage: 69.9 KB

In [37]:
df['Army'].value_counts()

Army
не призовут (по разным причинам)    149
могут призвать                       37
Name: count, dtype: int64

In [38]:
army_persons = df[df['Army'] == 'могут призвать']

In [39]:
free_persons = df[df['Army'] == 'не призовут (по разным причинам)']

In [40]:
army_persons['Hair length'].mean()

np.float64(11.045945945945945)

In [41]:
free_persons['Hair length'].mean()

np.float64(40.15570469798658)

In [42]:
without_friends = df[df['Friend number'] == 0]

In [43]:
without_friends['Sex'].value_counts()

Sex
мужской    1
женский    1
Name: count, dtype: int64

In [44]:
df['Animal'].value_counts()

Animal
Кошек                     115
Собак                      60
Ненавижу этих животных     11
Name: count, dtype: int64

In [45]:
dor_lovers = df[df['Animal'] == 'Собак']

In [46]:
dor_lovers['Floor number'].value_counts()

Floor number
4     12
1      7
5      6
2      5
6      5
7      4
9      3
3      3
11     3
10     2
12     2
8      2
14     2
16     1
17     1
15     1
13     1
Name: count, dtype: int64

In [47]:
dor_lovers[dor_lovers['Floor number'] == 1].describe()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Height of 5000 mm,Width of 5000 mm,Putin age,Hair length,Floor number,Social network duration min,City population,MIddle and index finger,Middle and ring finger,Middle and little finger
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,...,7.000000,7.000000,7.000000,7.000000,7.0,7.000000,7.000000,7.000000,7.000000,7.000000
mean,18.428571,173.428571,40.857143,1.714286,2003.285714,60.571429,85.571429,46.285714,6.571429,37.571429,...,60.285714,270.000000,14342.571429,22.428571,1.0,431.428571,868571.428571,10.714286,15.285714,33.428571
std,0.534522,9.589180,3.132016,0.951190,0.487950,58.798688,12.163568,42.307266,17.386366,46.932068,...,15.934389,312.409987,37771.375749,15.153186,0.0,438.954385,122532.794444,3.903600,9.250483,6.996598
min,18.000000,161.000000,36.000000,0.000000,2003.000000,0.000000,66.000000,0.000000,0.000000,0.000000,...,42.000000,100.000000,62.000000,5.000000,1.0,30.000000,700000.000000,5.000000,4.000000,20.000000
25%,18.000000,164.500000,39.000000,1.500000,2003.000000,11.500000,78.000000,2.000000,0.000000,0.000000,...,50.000000,120.000000,65.500000,8.500000,1.0,105.000000,780000.000000,8.500000,10.000000,32.000000
50%,18.000000,180.000000,42.000000,2.000000,2003.000000,50.000000,87.000000,74.000000,0.000000,0.000000,...,60.000000,150.000000,67.000000,25.000000,1.0,240.000000,850000.000000,10.000000,12.000000,35.000000
75%,19.000000,181.000000,43.000000,2.000000,2003.500000,97.500000,96.000000,79.000000,0.000000,85.500000,...,65.000000,215.000000,69.000000,35.000000,1.0,730.000000,985000.000000,13.500000,20.500000,37.500000
max,19.000000,182.000000,44.000000,3.000000,2004.000000,156.000000,98.000000,88.000000,46.000000,92.000000,...,90.000000,970.000000,100000.000000,40.000000,1.0,1080.000000,1000000.000000,16.000000,30.000000,40.000000

In [48]:
dor_lovers.describe()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Height of 5000 mm,Width of 5000 mm,Putin age,Hair length,Floor number,Social network duration min,City population,MIddle and index finger,Middle and ring finger,Middle and little finger
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,...,60.000000,60.000000,60.000000,60.000000,60.000000,6.000000e+01,6.000000e+01,60.000000,60.000000,60.000000
mean,20.166667,171.616667,40.033333,3.233333,2001.216667,215.033333,81.583333,61.300000,16.216667,36.183333,...,58.733333,146.366667,1766.966667,31.916667,6.183333,1.679424e+09,8.864133e+05,9.616667,9.286667,31.376667
std,1.975843,8.795399,2.597043,2.028330,2.630278,254.128352,10.732955,28.861622,28.111818,39.736629,...,20.413411,126.871744,12899.308414,25.983072,4.180227,1.290865e+10,9.830784e+05,3.809407,5.415936,30.756079
min,17.000000,153.000000,35.000000,0.000000,1988.000000,0.000000,59.000000,0.000000,0.000000,0.000000,...,4.000000,0.000000,53.000000,1.500000,1.000000,2.000000e+00,1.000000e+00,2.000000,1.000000,3.600000
25%,19.000000,166.000000,38.000000,2.000000,2000.000000,88.000000,72.750000,56.000000,0.000000,0.000000,...,50.000000,100.000000,67.000000,10.000000,3.750000,1.200000e+02,7.000000e+05,7.000000,5.000000,21.000000
50%,19.500000,170.000000,40.000000,3.000000,2002.000000,138.500000,82.500000,74.000000,0.000000,0.000000,...,60.000000,141.000000,69.000000,25.000000,5.000000,2.400000e+02,8.000000e+05,10.000000,8.000000,25.000000
75%,21.000000,180.000000,42.000000,4.000000,2003.000000,271.500000,89.500000,78.250000,39.500000,75.750000,...,70.000000,170.000000,71.000000,45.000000,9.000000,4.800000e+02,9.000000e+05,12.000000,12.000000,35.000000
max,26.000000,191.000000,45.000000,7.000000,2004.000000,1776.000000,98.000000,100.000000,91.000000,98.000000,...,100.000000,970.000000,100000.000000,100.000000,17.000000,1.000000e+11,8.000000e+06,20.000000,30.000000,250.000000

In [49]:
round(7 / 60 * 100, 0)

12.0

In [50]:
dor_lovers = df[df['Animal'] == 'Собак']
floor1 = dor_lovers[dor_lovers['Floor number'] == 1]
percent = round(len(floor1) / len(dor_lovers) * 100)
print(f'Способ 1: процент живущих на 1 этаже = {percent}%')

Способ 1: процент живущих на 1 этаже = 12%

In [51]:
all_people = dor_lovers.shape[0]
floor1_2 = dor_lovers[dor_lovers['Floor number'] == 1].shape[0]
percent2 = round(floor1_2 / all_people * 100)
print(f'Способ 2: процент живущих на 1 этаже = {percent2}%')

Способ 2: процент живущих на 1 этаже = 12%

In [52]:
dor_lovers = df[df['Animal'] == 'Собак']
percent3 = round((dor_lovers['Floor number'] == 1).mean() * 100)
print(f'Способ 3: процент живущих на 1 этаже = {percent3}%')

Способ 3: процент живущих на 1 этаже = 12%

In [66]:
percent = (df['Maths rating'] > 60).mean() * 100
print(f'{round(percent)}% студентов с рейтингом по математике выше 60 баллов')

68% студентов с рейтингом по математике выше 60 баллов

In [54]:
df['Brother-sister'].value_counts()

Brother-sister
есть брат                 62
есть сестра               55
нет ни брата ни сестры    39
есть и брат и сестра      30
Name: count, dtype: int64

In [55]:
single_child = df[df['Brother-sister'] == 'нет ни брата ни сестры']
median1 = single_child['Social network duration min'].median()
print(f'Длительность {round(median1)}')

Длительность 240

In [56]:
not_single_child = df[(df['Brother-sister'] == 'есть брат') | (df['Brother-sister'] == 'есть сестра')]
median2 = not_single_child['Social network duration min'].median()
print(f'Длительность {round(median2)}')

Длительность 180

In [57]:
difference_duration = round(median1 - median2)
print(f'Разница составляет {difference_duration} минут')

Разница составляет 60 минут

In [58]:
df['Fastfood'].value_counts()

Fastfood
KFC                                                82
Бургер кинг                                        56
Макдональдс (или как он там сейчас называется?)    48
Name: count, dtype: int64

In [59]:
KFC_persons = df[df['Fastfood'] == 'KFC']
avg_KFC_weight = KFC_persons['Weight'].mean()
print(f'Средний вес {round(avg_KFC_weight)} кг')

Средний вес 67 кг

In [60]:
Burger_persons = df[df['Fastfood'] == 'Бургер кинг']
avg_Burger_weight = Burger_persons['Weight'].mean()
print(f'Средний вес {round(avg_Burger_weight)} кг')

Средний вес 64 кг

In [61]:
Mac_persons = df[df['Fastfood'] == 'Макдональдс (или как он там сейчас называется?)']
avg_Mac_weight = Mac_persons['Weight'].mean()
print(f'Средний вес {round(avg_Mac_weight)} кг')

Средний вес 59 кг

In [62]:
dif_weight = round(avg_KFC_weight - avg_Mac_weight)
print(f'Средний вес студентов, употребляющих KFC, больше на {dif_weight} кг')

Средний вес студентов, употребляющих KFC, больше на 8 кг