Подключение библиотеки для работы с таблицами

In [ ]:
import pandas as pd
print(pd.__version__)
#Подключение библиотеки для работы с таблицами

3.0.3

Работа математических вычислений

In [ ]:
124/12, (1+56)/68, 40/8/5

(10.333333333333334, 0.8382352941176471, 1.0)

Задача. У вкладчика было 15600 рублей. Он положил их в банк под 9% годовых. Спустя год он переложил все свои деньги в другой банк под 16% годовых. Сколько всего денег у него будет к концу второго года.

In [ ]:
#ответ
15600 * 0.09 * 0.16

224.64000000000001

Начало работы с загруженной таблицей через методы pandas

In [ ]:
df= pd.read_csv(r'C:\Users\nikry\fintech_analysis\students.csv', delimiter = ',') 
#чтение csv файла и загрузка в пременную

In [ ]:
df.info()
#вывод информации о таблице

<class 'pandas.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    str
 23  Sex                          186 non-null    str
 24  Problems in last semester    186 non-null    str
 25  Coin                         186 non-null    str
 26  Rock paper scissors          186 non-null    str
 27  Animal                       186 non-null    str
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    str
 30  Fastfood                     186 non-null    str
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    str
 35  Hostel                       186 non-null    str
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    str
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    str
 42  Your insitute                186 non-null    str
 43  Brother-sister               186 non-null    str
 44  Plane seat                   186 non-null    str
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), str(15)
memory usage: 69.9 KB

In [ ]:
df.shape
#метод для получения количества строк и столбцов таблицы

(186, 48)

In [ ]:
df
#вывод всей таблицы

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,23,168,39,7,1999,228,93,68,0,0,...,300,Твикс,770000.0,Естественный (биология-химия-физика-технари),Естественный (биология-химия-физика-технари),нет ни брата ни сестры,У окна (пардон: у иллюминатора),13,23.0,45.0
182,19,169,38,1,2003,0,73,5,0,0,...,75,M&Ms,1250000.0,Педагогический,СоцГум,есть сестра,У окна (пардон: у иллюминатора),8,9.0,15.0
183,18,161,37,2,2003,11,98,0,0,0,...,460,Твикс,1000000.0,Естественный (биология-химия-физика-технари),Другое,есть и брат и сестра,У окна (пардон: у иллюминатора),9,16.0,35.0
184,19,169,41,1,2003,22,82,86,0,0,...,540,Твикс,850000.0,Естественный (биология-химия-физика-технари),Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),9,15.0,25.0
185,18,164,39,2,2003,500,94,5,0,0,...,400,Твикс,800000.0,Юридический,СоцГум,нет ни брата ни сестры,У окна (пардон: у иллюминатора),7,10.0,35.0

In [ ]:
df.head()
#вывод на экран первых 5 строк таблицы

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0

In [ ]:
df.tail()
#вывод на экран последних 5 строк таблицы

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
181,23,168,39,7,1999,228,93,68,0,0,...,300,Твикс,770000.0,Естественный (биология-химия-физика-технари),Естественный (биология-химия-физика-технари),нет ни брата ни сестры,У окна (пардон: у иллюминатора),13,23.0,45.0
182,19,169,38,1,2003,0,73,5,0,0,...,75,M&Ms,1250000.0,Педагогический,СоцГум,есть сестра,У окна (пардон: у иллюминатора),8,9.0,15.0
183,18,161,37,2,2003,11,98,0,0,0,...,460,Твикс,1000000.0,Естественный (биология-химия-физика-технари),Другое,есть и брат и сестра,У окна (пардон: у иллюминатора),9,16.0,35.0
184,19,169,41,1,2003,22,82,86,0,0,...,540,Твикс,850000.0,Естественный (биология-химия-физика-технари),Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),9,15.0,25.0
185,18,164,39,2,2003,500,94,5,0,0,...,400,Твикс,800000.0,Юридический,СоцГум,нет ни брата ни сестры,У окна (пардон: у иллюминатора),7,10.0,35.0

In [ ]:
df.head(10)
#вывод на экран первых 10 строк таблицы

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0
5,18,177,40,2,2003,100,70,68,0,75,...,250,Сникерс,1200000.0,СоцГум,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),12,7.0,30.0
6,18,180,42,0,2004,0,66,4,0,0,...,30,Сникерс,700000.0,Педагогический,Юридический,есть брат,У окна (пардон: у иллюминатора),5,30.0,35.0
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0
8,20,185,46,3,2002,28,87,76,0,0,...,120,Скиттлс (хотя это и не шоколадка),800000.0,Естественный (биология-химия-физика-технари),Экономический,есть брат,В середине,5,3.0,15.0
9,22,168,38,6,2000,297,71,5,0,0,...,40,Милки Вей,860.0,Математический и ИТ,СоцГум,есть брат,У окна (пардон: у иллюминатора),15,10.0,40.0

In [ ]:
df.head(13)

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0
5,18,177,40,2,2003,100,70,68,0,75,...,250,Сникерс,1200000.0,СоцГум,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),12,7.0,30.0
6,18,180,42,0,2004,0,66,4,0,0,...,30,Сникерс,700000.0,Педагогический,Юридический,есть брат,У окна (пардон: у иллюминатора),5,30.0,35.0
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0
8,20,185,46,3,2002,28,87,76,0,0,...,120,Скиттлс (хотя это и не шоколадка),800000.0,Естественный (биология-химия-физика-технари),Экономический,есть брат,В середине,5,3.0,15.0
9,22,168,38,6,2000,297,71,5,0,0,...,40,Милки Вей,860.0,Математический и ИТ,СоцГум,есть брат,У окна (пардон: у иллюминатора),15,10.0,40.0
10,20,158,35,4,2001,1000,85,72,0,0,...,600,КитКат,800000.0,Педагогический,Естественный (биология-химия-физика-технари),есть и брат и сестра,У прохода,10,9.0,15.0
11,19,183,44,2,2002,40,5,5,0,6,...,300,КитКат,880000.0,Математический и ИТ,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),9,10.0,15.0
12,21,169,39,4,2001,150,68,27,0,0,...,240,M&Ms,800.0,Педагогический,Экономический,есть сестра,В середине,9,11.0,25.0

In [ ]:
df.tail(18)
#вывод на экран последних 18 строк таблицы

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
168,22,161,38,7,2000,50,91,74,0,0,...,1800,Натс,850000.0,Математический и ИТ,Другое,есть брат,У окна (пардон: у иллюминатора),5,13.0,35.0
169,21,160,37,4,2001,221,94,76,0,0,...,0,Сникерс,800000.0,Педагогический,Экономический,нет ни брата ни сестры,У окна (пардон: у иллюминатора),9,10.0,32.0
170,22,168,38,4,2000,49,100,56,0,0,...,240,КитКат,500000.0,Педагогический,Экономический,нет ни брата ни сестры,У окна (пардон: у иллюминатора),10,5.0,20.0
171,20,162,37,2,2002,70,82,0,0,0,...,540,Твикс,900.0,СоцГум,Юридический,есть сестра,У прохода,4,11.0,25.0
172,21,164,37,4,2000,260,86,0,0,0,...,60,Милки Вей,900000.0,Математический и ИТ,СоцГум,есть брат,У окна (пардон: у иллюминатора),10,6.0,30.0
173,29,176,39,7,1992,233,72,69,0,0,...,60,Сникерс,850000.0,Математический и ИТ,Экономический,есть сестра,У окна (пардон: у иллюминатора),7,11.0,30.0
174,20,158,37,3,2001,21,91,56,0,0,...,120,Милки Вей,700000.0,Математический и ИТ,Естественный (биология-химия-физика-технари),нет ни брата ни сестры,У прохода,9,10.0,35.0
175,18,176,38,2,2003,183,90,0,0,0,...,240,Марс,854627.0,Естественный (биология-химия-физика-технари),СоцГум,есть сестра,У окна (пардон: у иллюминатора),16,13.0,28.0
176,21,162,38,7,2000,150,89,0,0,0,...,300,Твикс,800000.0,СоцГум,СоцГум,есть и брат и сестра,У окна (пардон: у иллюминатора),13,12.0,40.0
177,23,155,36,6,1999,90,91,51,0,0,...,100,Баунти,900000.0,Математический и ИТ,Математический и ИТ,есть сестра,У окна (пардон: у иллюминатора),5,4.0,3.0
178,21,170,39,4,2001,123,76,0,0,0,...,360,Сникерс,800000.0,СоцГум,Юридический,есть и брат и сестра,У окна (пардон: у иллюминатора),3,2.0,7.0
179,20,176,42,3,2001,80,85,0,0,0,...,120,Сникерс,700000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),5,5.0,20.0
180,21,167,36,4,2000,120,98,56,0,0,...,120,Твикс,8000000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,5.0,25.0
181,23,168,39,7,1999,228,93,68,0,0,...,300,Твикс,770000.0,Естественный (биология-химия-физика-технари),Естественный (биология-химия-физика-технари),нет ни брата ни сестры,У окна (пардон: у иллюминатора),13,23.0,45.0
182,19,169,38,1,2003,0,73,5,0,0,...,75,M&Ms,1250000.0,Педагогический,СоцГум,есть сестра,У окна (пардон: у иллюминатора),8,9.0,15.0
183,18,161,37,2,2003,11,98,0,0,0,...,460,Твикс,1000000.0,Естественный (биология-химия-физика-технари),Другое,есть и брат и сестра,У окна (пардон: у иллюминатора),9,16.0,35.0
184,19,169,41,1,2003,22,82,86,0,0,...,540,Твикс,850000.0,Естественный (биология-химия-физика-технари),Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),9,15.0,25.0
185,18,164,39,2,2003,500,94,5,0,0,...,400,Твикс,800000.0,Юридический,СоцГум,нет ни брата ни сестры,У окна (пардон: у иллюминатора),7,10.0,35.0

In [ ]:
df['Age']
#обращение к столбцу с признаком возраста

0      20
1      22
2      21
3      19
4      23
       ..
181    23
182    19
183    18
184    19
185    18
Name: Age, Length: 186, dtype: int64

In [ ]:
df['Age'].describe()
#вывод математических показателей о принаке (количество строк; среднее значение; отклонение; процентиль студентов, возраст которых до 19 лет; медиана; процентиль студентов, возраст которых до 21 года)

count    186.000000
mean      20.688172
std        3.468713
min       17.000000
25%       19.000000
50%       20.000000
75%       21.000000
max       55.000000
Name: Age, dtype: float64

In [ ]:
df['Growth'].describe()

count    186.000000
mean     170.661290
std        9.055881
min      153.000000
25%      164.000000
50%      169.000000
75%      178.000000
max      197.000000
Name: Growth, dtype: float64

In [ ]:
df['Sex'].describe()
#вывод описания о категориях признака (количество срок, количество уникальных категорий, название преобладающей категории и количество строк, где значение столбца- преобладающая категория)

count         186
unique          2
top       женский
freq          120
Name: Sex, dtype: object

In [ ]:
df['Sex'].value_counts()
#метод считает количество строк по каждой категории

Sex
женский    120
мужской     66
Name: count, dtype: int64

In [ ]:
df['Chocolate'].value_counts()

Chocolate
КитКат                               35
Сникерс                              34
Твикс                                34
Баунти                               30
Милки Вей                            17
Натс                                 13
Марс                                 11
M&Ms                                  8
Скиттлс (хотя это и не шоколадка)     4
Name: count, dtype: int64

In [ ]:
df.describe()
#описание каждого признака(поля, столбца) с числовым типом данных

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Height of 5000 mm,Width of 5000 mm,Putin age,Hair length,Floor number,Social network duration min,City population,MIddle and index finger,Middle and ring finger,Middle and little finger
count,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,...,186.000000,186.000000,186.000000,186.000000,186.000000,1.860000e+02,1.860000e+02,186.000000,186.000000,186.000000
mean,20.688172,170.661290,39.715054,3.500000,1991.107527,374.032258,81.634409,58.177419,13.182796,32.801075,...,75.720430,177.688172,690.236559,34.365054,6.322581,5.417500e+08,7.946669e+05,9.741935,9.705376,28.798925
std,3.468713,9.055881,2.814920,3.147285,132.099550,2199.541507,14.325019,29.575478,26.414552,38.992282,...,107.747088,240.978320,7360.321689,25.672211,4.338791,7.332267e+09,6.093052e+05,4.385241,6.894963,19.710011
min,17.000000,153.000000,34.000000,0.000000,200.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,42.000000,0.200000,1.000000,0.000000e+00,1.000000e+00,0.000000,0.000000,0.000000
25%,19.000000,164.000000,38.000000,2.000000,2000.000000,74.500000,76.000000,50.000000,0.000000,0.000000,...,50.000000,100.000000,67.000000,12.000000,3.000000,1.200000e+02,7.000000e+05,7.000000,6.000000,20.000000
50%,20.000000,169.000000,39.000000,3.000000,2001.500000,130.000000,85.000000,70.000000,0.000000,0.000000,...,60.000000,140.000000,69.000000,30.000000,5.000000,2.000000e+02,8.000000e+05,10.000000,10.000000,28.500000
75%,21.000000,178.000000,42.000000,4.000000,2003.000000,236.000000,91.000000,76.750000,0.000000,75.000000,...,70.000000,167.250000,70.000000,50.000000,8.000000,3.600000e+02,8.845000e+05,12.000000,12.000000,35.000000
max,55.000000,197.000000,48.000000,37.000000,2004.000000,30000.000000,100.000000,100.000000,97.000000,98.000000,...,950.000000,1800.000000,100000.000000,150.000000,20.000000,1.000000e+11,8.000000e+06,30.000000,80.000000,250.000000