Групировка, сортировка и корреляция

In [2]:
import pandas as pd
df= pd.read_csv(r'C:\Users\nikry\fintech_analysis\students.csv', delimiter = ',') 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    str
 23  Sex                          186 non-null    str
 24  Problems in last semester    186 non-null    str
 25  Coin                         186 non-null    str
 26  Rock paper scissors          186 non-null    str
 27  Animal                       186 non-null    str
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    str
 30  Fastfood                     186 non-null    str
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    str
 35  Hostel                       186 non-null    str
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    str
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    str
 42  Your insitute                186 non-null    str
 43  Brother-sister               186 non-null    str
 44  Plane seat                   186 non-null    str
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), str(15)
memory usage: 69.9 KB

In [3]:
df_cut = df[['Age', 'Growth', 'Weight']]
df_cut.head()

   Age  Growth  Weight
0   20     170    64.0
1   22     191    73.0
2   21     172    60.0
3   19     168    59.0
4   23     159    57.0

Сортировка

In [ ]:
df_cut.sort_values(by = 'Age', ascending=False)
#Отсортировали таблицу по убыванию возраста

     Age  Growth  Weight
81    55     160     3.0
63    35     180    78.0
99    31     165    53.0
173   29     176    70.0
82    27     168    58.0
..   ...     ...     ...
127   18     165    46.0
185   18     164    54.0
175   18     176    58.0
115   17     175    72.0
126   17     168    71.0

[186 rows x 3 columns]

In [ ]:
df_cut.sort_values('Growth', ascending = True)
#Отсортировали таблицу по увеличению роста

     Age  Growth  Weight
152   19     153    46.0
34    19     155     NaN
177   23     155    50.0
53    19     156    48.0
117   20     157     NaN
..   ...     ...     ...
33    22     188    95.0
87    23     188    83.0
1     22     191    73.0
27    19     193    61.0
103   19     197   100.0

[186 rows x 3 columns]

In [ ]:
df_cut.sort_values(['Age', 'Growth'], ascending = [False, False])
#Отсортировали таблицу по убыванию возраста и убыванию роста(в случае если у разных студентов возраст будет одинаковым)

     Age  Growth  Weight
81    55     160     3.0
63    35     180    78.0
99    31     165    53.0
173   29     176    70.0
82    27     168    58.0
..   ...     ...     ...
47    18     159     NaN
94    18     158    53.0
118   18     157    59.0
115   17     175    72.0
126   17     168    71.0

[186 rows x 3 columns]

In [ ]:
df_cut.sort_values(['Growth', 'Age'], ascending = [False, False])
#Отсортировали таблицу по убыванию роста и убыванию возраста(в случае если  у разных студентов рост будет одинаковым)

     Age  Growth  Weight
103   19     197   100.0
27    19     193    61.0
1     22     191    73.0
87    23     188    83.0
33    22     188    95.0
..   ...     ...     ...
118   18     157    59.0
53    19     156    48.0
177   23     155    50.0
34    19     155     NaN
152   19     153    46.0

[186 rows x 3 columns]

In [8]:
df_sorted = df_cut.sort_values('Growth', ascending = False)

In [19]:
df_sorted.iloc[3,] 
#Обратились по уникальному индексу (номеру строки), то есть вывели данные о четвёртом по счёту студенте

Age        22.0
Growth    188.0
Weight     95.0
Name: 33, dtype: float64

In [ ]:
df_sorted.iloc[3,0] 
#Вторым параметром задали вывод определённого столбца (в данном случае столбца с признаком возраста)

np.int64(22)

Добавление нового стоблца

In [20]:
df_cut['Mass index'] = 10000*df_cut['Weight'] / (df_cut['Growth'] * df_cut['Growth'])
#Добавили столбец с индексом массы тела

In [22]:
df_cut.head()

   Age  Growth  Weight  Mass index
0   20     170    64.0   22.145329
1   22     191    73.0   20.010416
2   21     172    60.0   20.281233
3   19     168    59.0   20.904195
4   23     159    57.0   22.546576

In [24]:
df_cut.sort_values('Mass index', ascending = False)

     Age  Growth  Weight  Mass index
149   22     173   115.0   38.424271
7     19     180   120.0   37.037037
28    20     163    90.0   33.874064
124   21     163    88.0   33.121307
69    20     181   105.0   32.050304
..   ...     ...     ...         ...
158   21     168     NaN         NaN
161   24     163     NaN         NaN
167   21     168     NaN         NaN
170   22     168     NaN         NaN
178   21     170     NaN         NaN

[186 rows x 4 columns]

Коэффициент корреляции (КК)

In [25]:
df_cut.corr()

                 Age    Growth    Weight  Mass index
Age         1.000000 -0.101982 -0.185722   -0.200305
Growth     -0.101982  1.000000  0.544528    0.146201
Weight     -0.185722  0.544528  1.000000    0.904678
Mass index -0.200305  0.146201  0.904678    1.000000

Группировка

In [30]:
df.groupby('Sex')[['Growth','Weight']].mean()

             Growth     Weight
Sex
женский  165.725000  59.105263
мужской  179.636364  71.580645

In [34]:
df.groupby(['Sex', 'Chocolate'])[['Russian rating', 'Maths rating']].mean()

                                           Russian rating  Maths rating
Sex     Chocolate
женский M&Ms                                    79.400000     51.600000
        Баунти                                  81.181818     56.318182
        КитКат                                  85.782609     61.782609
        Марс                                    91.166667     36.666667
        Милки Вей                               79.583333     45.250000
        Натс                                    84.636364     53.818182
        Скиттлс (хотя это и не шоколадка)       86.000000     67.000000
        Сникерс                                 80.375000     61.562500
        Твикс                                   86.478261     55.217391
мужской M&Ms                                    83.666667     76.666667
        Баунти                                  78.375000     68.000000
        КитКат                                  74.416667     51.083333
        Марс                                    85.600000     55.400000
        Милки Вей                               72.800000     61.800000
        Натс                                    70.500000     72.000000
        Скиттлс (хотя это и не шоколадка)       84.000000     77.000000
        Сникерс                                 77.666667     59.055556
        Твикс                                   79.818182     75.000000

In [33]:
df.groupby('Chocolate')[['Russian rating','Maths rating']].mean()

                                   Russian rating  Maths rating
Chocolate
M&Ms                                    81.000000     61.000000
Баунти                                  80.433333     59.433333
КитКат                                  81.885714     58.114286
Марс                                    88.636364     45.181818
Милки Вей                               77.588235     50.117647
Натс                                    82.461538     56.615385
Скиттлс (хотя это и не шоколадка)       85.000000     72.000000
Сникерс                                 78.941176     60.235294
Твикс                                   84.323529     61.617647

Решение практических задач по третьему уроку

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    str
 23  Sex                          186 non-null    str
 24  Problems in last semester    186 non-null    str
 25  Coin                         186 non-null    str
 26  Rock paper scissors          186 non-null    str
 27  Animal                       186 non-null    str
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    str
 30  Fastfood                     186 non-null    str
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    str
 35  Hostel                       186 non-null    str
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    str
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    str
 42  Your insitute                186 non-null    str
 43  Brother-sister               186 non-null    str
 44  Plane seat                   186 non-null    str
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), str(15)
memory usage: 69.9 KB

In [37]:
df_cut2 = df[['Year of birth', 'Growth', 'Weight', 'Hair length', 'Shoe size']]

In [38]:
df_cut2.sort_values('Shoe size', ascending = True)

     Year of birth  Growth  Weight  Hair length  Shoe size
96            2003     163    56.0         50.0         34
10            2001     158    47.0         50.0         35
47            2004     159     NaN         25.0         35
52            2002     163    53.0         55.0         35
118           2003     157    59.0         30.0         35
..             ...     ...     ...          ...        ...
76            2002     184     NaN         20.0         45
103           2002     197   100.0         23.0         46
8             2002     185    69.0         25.0         46
27            2003     193    61.0          3.0         48
7             2003     180   120.0         20.0         48

[186 rows x 5 columns]

In [39]:
df_cut2.sort_values('Shoe size', ascending = False)

     Year of birth  Growth  Weight  Hair length  Shoe size
7             2003     180   120.0         20.0         48
27            2003     193    61.0          3.0         48
8             2002     185    69.0         25.0         46
103           2002     197   100.0         23.0         46
55            1999     180    92.0          0.2         45
..             ...     ...     ...          ...        ...
10            2001     158    47.0         50.0         35
116           1999     158    48.0         55.0         35
118           2003     157    59.0         30.0         35
138           2001     158     NaN        100.0         35
96            2003     163    56.0         50.0         34

[186 rows x 5 columns]

In [44]:
df_cut2.sort_values(['Shoe size', 'Growth'], ascending = [True, True]).head(9)

     Year of birth  Growth  Weight  Hair length  Shoe size
96            2003     163    56.0         50.0         34
118           2003     157    59.0         30.0         35
10            2001     158    47.0         50.0         35
37            1997     158    60.0         60.0         35
116           1999     158    48.0         55.0         35
138           2001     158     NaN        100.0         35
47            2004     159     NaN         25.0         35
52            2002     163    53.0         55.0         35
177           1999     155    50.0         70.0         36

In [45]:
df_cut2.sort_values(['Shoe size', 'Growth'], ascending = [True, False])

     Year of birth  Growth  Weight  Hair length  Shoe size
96            2003     163    56.0         50.0         34
52            2002     163    53.0         55.0         35
47            2004     159     NaN         25.0         35
10            2001     158    47.0         50.0         35
37            1997     158    60.0         60.0         35
..             ...     ...     ...          ...        ...
55            1999     180    92.0          0.2         45
103           2002     197   100.0         23.0         46
8             2002     185    69.0         25.0         46
27            2003     193    61.0          3.0         48
7             2003     180   120.0         20.0         48

[186 rows x 5 columns]

In [46]:
df_cut2.sort_values(['Shoe size', 'Growth'], ascending = [False, True])

     Year of birth  Growth  Weight  Hair length  Shoe size
7             2003     180   120.0         20.0         48
27            2003     193    61.0          3.0         48
8             2002     185    69.0         25.0         46
103           2002     197   100.0         23.0         46
55            1999     180    92.0          0.2         45
..             ...     ...     ...          ...        ...
116           1999     158    48.0         55.0         35
138           2001     158     NaN        100.0         35
47            2004     159     NaN         25.0         35
52            2002     163    53.0         55.0         35
96            2003     163    56.0         50.0         34

[186 rows x 5 columns]

In [51]:
df_cut2['Full length'] = df_cut2['Growth'] + df_cut2['Hair length']
max_length = df_cut2['Full length'].max()
print(f'Максимальное значение признака равно {round(max_length)} см')

Максимальное значение признака равно 319 см

In [52]:
df_cut2.corr()

,Year of birth,Growth,Weight,Hair length,Shoe size,Full length
Year of birth,1.000000,-0.113357,0.006042,0.095402,-0.108360,0.064713
Growth,-0.113357,1.000000,0.544528,-0.554408,0.863252,-0.235492
Weight,0.006042,0.544528,1.000000,-0.319416,0.591149,-0.145316
Hair length,0.095402,-0.554408,-0.319416,1.000000,-0.567568,0.939398
Shoe size,-0.108360,0.863252,0.591149,-0.567568,1.000000,-0.307190
Full length,0.064713,-0.235492,-0.145316,0.939398,-0.307190,1.000000

In [53]:
df.groupby('Glasses')[['Russian rating','Maths rating']].mean()

                                     Russian rating  Maths rating
Glasses
да                                        83.388235     56.741176
нет                                       80.471910     59.955056
простите. не увидел(а) вопроса ))))       77.900000     54.700000

In [54]:
df.groupby('Rock paper scissors')[['Russian rating','Maths rating']].mean()

                     Russian rating  Maths rating
Rock paper scissors
Бумага                    76.473684     52.894737
Камень                    81.450000     62.166667
Ножницы                   83.988636     57.738636